### PR TITLE
Support Python 3

### PR DESCRIPTION
**Pull request by pnuu**
This PR adds support to Python 3 by replacing print statements with print function and adding try/except cases for imports.

### CODE REVIEW

**Comment by pnuu** [comment]
It seems that most of the fixes were already done in another branch that got merged after I started with my modifications. There are some autopep8 updates, and different ordering in the imports (by default try the Python 3, fallback on Python 2 version).

**Comment by pnuu** [comment]
There are incorrect syntax in current master and develop in satpass.py except statements, which are fixed here.

**Comment by adybbroe** [comment]
@pnuu Can we merge this now? Or is there more to it?

**Comment by pnuu** [comment]
The features I have used (via pytroll-collectors/gatherer.py) work, and so should everythung else. I don't have anything else to commit to this :-)

**Pull request merged**
