### PR TITLE
Fix nasa ftp retrieval

### PR DESCRIPTION
**Pull request by adybbroe**
NASA has changed to no longer support plain FTP access for reasons of security.  Only FTPS or HTTPS is now supported by these servers.

Now we use ftplib.FTP_TLS instead of ftplib.FTP to connect to the nasa server in order to download Aqua/Terra downlink schedules

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [x] Tests passed 
 - [x] Passes ``git diff origin/master **/*py | flake8 --diff`` 
 - [ ] Fully documented

### CODE REVIEW

**Comment by adybbroe** [comment]
Well, my simple change from "FTP" to "FTP_TLS" was too simple, I will be back....

**Comment by adybbroe** [comment]
Ok, now I think we are ok

**Comment by adybbroe** [comment]
Can we please merge this @pnuu and @mraspaud ?

**Comment by adybbroe** [comment]
Ok, ready. Can I merge @pnuu ?

**Comment by pnuu** [comment]
If it works, why not. I don't use this feature myself, so can't test.

**Pull request merged**
