### PR TITLE
Fix ftp downloading for older python versions

### PR DESCRIPTION
**Pull request by mraspaud**
- [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Tests passed 
 - [ ] Passes ``git diff origin/main **/*py | flake8 --diff`` 
 - [ ] Fully documented

### CODE REVIEW

**Comment by mraspaud** [comment]
@TAlonglong if you want to have a look...

**Review by TAlonglong — APPROVED** [review]
I don't have any problem with this change

**Comment by TAlonglong** [comment]
Don't looks like I can merge it.

**Review by adybbroe — APPROVED** [review]
LGTM.
But we should leave python 2 all together shortly!

**Pull request merged**
